services:
  # Backend API service
  - type: web
    name: calendar-app-backend
    env: node
    region: oregon # You can change this to the region closest to your users
    buildCommand: npm run render-build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will use this port internally
      - key: MONGODB_URI
        sync: false # This will allow setting this secret from the Render dashboard
    plan: free # Specify the pricing plan, 'free' is the default free tier
  
  # Frontend static site
  - type: web
    name: calendar-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: calendar-app-backend
          type: web
          property: host
        value: https://$$host/api
    plan: free 